config/routes.rb
Rails.application.routes.draw do
  resources :exams
  resources :subs
  resources :subjects
  resources :departments
  resources :year_groups
  resources :events
  devise_for :users
  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  
  mount_uploader :image, EventImageUploader
  
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  def self.future
      where('date >= ?', Date.today)
  end
  
  def self.date_order
      order(date: :asc)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:user_id, :name, :description, :date, :start_time, :end_time, :status, :image)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="panel panel-info">
    <div class="panel-heading">
        <h2 class="panel-title">
            <%= event.name %>
            <span class="pull-right">
                <%= format_date_time(event.date, event.start_time, event.end_time) %>
            </span>
        </h2>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
                <%= image_tag event.image, class: 'img-responsive' %>
            </div>
            <div class="col-md-8">
                <p class="lead"><%= event.description %></p>
                <p></p>
                <%= link_to 'More info', event_path(event), class: 'btn btn-info btn-xs' %>
            </div>
        </div>
    </div>
</div>

app/views/events/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    
    <%= f.input :name, label: 'Enter the event name' %>
    <%= f.input :description, placeholder: 'Please provide details of the event' %>
    <%= f.input :date, order: [:day, :month, :year], start_year: Date.today.year, end_year: Date.today.year + 1 %>
    <%= f.input :start_time %>
    <%= f.input :end_time, as: :time %>
  
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table class="table">
  <thead>
    <tr>
     
      <th>Name</th>
      
      <th>Date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Status</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
       
        <td><%= event.name %></td>
       
        <td><%= event.date.strftime('%a, %d %b %y') %></td>
        <td><%= event.start_time.strftime('%l:%M%P') %></td>
        <td><%= event.end_time.strftime('%l:%M%P') %></td>
        <td><%= event.status %></td>
       
        <td><%= link_to 'Show', event, class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_event_path(event), class: 'btn btn-warning btn-xs' %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path, class: 'btn btn-success' %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title"><%= @event.name %></h2>
      </div>
      <div class="panel-body">
        
        <%= image_tag @event.image, class: 'img-responsive img-thumbnail' %>
        
        <p><%= @event.description %></p>
        <hr>
        <p><strong>When: </strong>
        <%= @event.date.strftime('%A, %d %B %Y') %> 
        <%= @event.start_time.strftime('%l:%M%P') %> - 
        <%= @event.end_time.strftime('%l:%M%P') %></p>
      </div>
    </div>
  </div>
</div>

<p>
  <strong>User's email:</strong>
  <%= @event.user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Status:</strong>
  <%= @event.status %>
</p>

<p>
  <strong>Image:</strong>
  <%= @event.image %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>