config/routes.rb
Rails.application.routes.draw do
  resources :exams
  resources :subs
  resources :subjects
  resources :departments
  resources :year_groups
  resources :events
  devise_for :users
  root 'home#index'

end

app/models/year_group.rb
class YearGroup < ActiveRecord::Base
    has_many :subs
end

app/controllers/year_groups_controller.rb
class YearGroupsController < ApplicationController
  before_action :set_year_group, only: [:show, :edit, :update, :destroy]

  # GET /year_groups
  # GET /year_groups.json
  def index
    @year_groups = YearGroup.all
  end

  # GET /year_groups/1
  # GET /year_groups/1.json
  def show
  end

  # GET /year_groups/new
  def new
    @year_group = YearGroup.new
  end

  # GET /year_groups/1/edit
  def edit
  end

  # POST /year_groups
  # POST /year_groups.json
  def create
    @year_group = YearGroup.new(year_group_params)

    respond_to do |format|
      if @year_group.save
        format.html { redirect_to @year_group, notice: 'Year group was successfully created.' }
        format.json { render :show, status: :created, location: @year_group }
      else
        format.html { render :new }
        format.json { render json: @year_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /year_groups/1
  # PATCH/PUT /year_groups/1.json
  def update
    respond_to do |format|
      if @year_group.update(year_group_params)
        format.html { redirect_to @year_group, notice: 'Year group was successfully updated.' }
        format.json { render :show, status: :ok, location: @year_group }
      else
        format.html { render :edit }
        format.json { render json: @year_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /year_groups/1
  # DELETE /year_groups/1.json
  def destroy
    @year_group.destroy
    respond_to do |format|
      format.html { redirect_to year_groups_url, notice: 'Year group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_year_group
      @year_group = YearGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def year_group_params
      params.require(:year_group).permit(:name)
    end
end

app/helpers/year_groups_helper.rb
module YearGroupsHelper
end

app/views/year_groups/_form.html.erb
<%= simple_form_for(@year_group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/year_groups/edit.html.erb
<h1>Editing Year Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @year_group %> |
<%= link_to 'Back', year_groups_path %>

app/views/year_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Year Groups</h1>

    <% @year_groups.each do |year_group| %>
      
<div class ="col-md-6">
  <%=link_to year_group.name,subjects_path(year: year_group.id),class: "year_group" %>
 </div> 
       <!--<td><%= link_to 'Show', year_group %></td>-->
        <!--<td><%= link_to 'Edit', edit_year_group_path(year_group) %></td>-->
        <!--<td><%= link_to 'Destroy', year_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
     
    <% end %>
<%= link_to "Add subject",new_sub_path%>

<!--<br>-->

<!--<%= link_to 'New Year group', new_year_group_path %>-->

app/views/year_groups/new.html.erb
<h1>New Year Group</h1>

<%= render 'form' %>

<%= link_to 'Back', year_groups_path %>

app/views/year_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @year_group.name %>
</p>

<%= link_to 'Edit', edit_year_group_path(@year_group) %> |
<%= link_to 'Back', year_groups_path %>