config/routes.rb
Rails.application.routes.draw do
  resources :exams
  resources :subs
  resources :subjects
  resources :departments
  resources :year_groups
  resources :events
  devise_for :users
  root 'home#index'

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  belongs_to :year_group
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :set_sub, only: [:show, :edit, :update, :destroy]

  # GET /subs
  # GET /subs.json
  def index
    @subs = Sub.where(year_group_id: params[:year])
  end

  # GET /subs/1
  # GET /subs/1.json
  def show
  end

  # GET /subs/new
  def new
    @sub = Sub.new
  end

  # GET /subs/1/edit
  def edit
  end

  # POST /subs
  # POST /subs.json
  def create
    @sub = Sub.new(sub_params)
    # @sub.year_group_id = @year_group.id

    respond_to do |format|
      if @sub.save
        format.html { redirect_to @sub, notice: 'Sub was successfully created.' }
        format.json { render :show, status: :created, location: @sub }
      else
        format.html { render :new }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subs/1
  # PATCH/PUT /subs/1.json
  def update
    respond_to do |format|
      if @sub.update(sub_params)
        format.html { redirect_to @sub, notice: 'Sub was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub }
      else
        format.html { render :edit }
        format.json { render json: @sub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subs/1
  # DELETE /subs/1.json
  def destroy
    @sub.destroy
    respond_to do |format|
      format.html { redirect_to subs_url, notice: 'Sub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub
      @sub = Sub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_params
      params.require(:sub).permit(:name, :year_group_id)
    end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<%= simple_form_for(@sub) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <!--<%= f.association :year_group %>-->
    <%= f.input :year_group_id, input_html: { value: params[:year_group]}, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subs/edit.html.erb
<h1>Editing Sub</h1>

<%= render 'form' %>

<%= link_to 'Show', @sub %> |
<%= link_to 'Back', subs_path %>

app/views/subs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subs.each do |sub| %>
      <tr>
        <td><%= sub.name %></td>
        <td><%= sub.year_group %></td>
        <td><%= link_to 'Show', sub %></td>
        <td><%= link_to 'Edit', edit_sub_path(sub) %></td>
        <td><%= link_to 'Destroy', sub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub', new_sub_path %>

app/views/subs/new.html.erb
<h1>New Sub</h1>

<%= render 'form' %>

<%= link_to 'Back', subs_path %>

app/views/subs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sub.name %>
</p>

<p>
  <strong>Year group:</strong>
  <%= @sub.year_group %>
</p>

<%= link_to 'Edit', edit_sub_path(@sub) %> |
<%= link_to 'Back', subs_path %>