config/routes.rb
Rails.application.routes.draw do
  resources :exams
  resources :subs
  resources :subjects
  resources :departments
  resources :year_groups
  resources :events
  devise_for :users
  root 'home#index'

end

app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :year_group
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:sub_name, :grade, :start_date, :start_time, :image, :description, :year_group_id)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= simple_form_for(@exam) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :sub_name %>
    <%= f.input :grade %>
    <%= f.input :start_date %>
    <%= f.input :start_time %>
    <%= f.input :image %>
    <%= f.input :description %>
    <%= f.association :year_group %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exams</h1>

<table>
  <thead>
    <tr>
      <th>Sub name</th>
      <th>Grade</th>
      <th>Start date</th>
      <th>Start time</th>
      <th>Image</th>
      <th>Description</th>
      <th>Year group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.sub_name %></td>
        <td><%= exam.grade %></td>
        <td><%= exam.start_date %></td>
        <td><%= exam.start_time %></td>
        <td><%= exam.image %></td>
        <td><%= exam.description %></td>
        <td><%= exam.year_group %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exam', new_exam_path %>

app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form' %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sub name:</strong>
  <%= @exam.sub_name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @exam.grade %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @exam.start_date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @exam.start_time %>
</p>

<p>
  <strong>Image:</strong>
  <%= @exam.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @exam.description %>
</p>

<p>
  <strong>Year group:</strong>
  <%= @exam.year_group %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>